services:
  github-scanner:
    build:
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}    
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_ORG=${GITHUB_ORG}
      - OLD_PR_THRESHOLD_DAYS=${OLD_PR_THRESHOLD_DAYS}
      - GITHUB_REPO=${GITHUB_REPO}
    volumes:
      - ./reports:/app/reports
    networks:
      - scanner-network
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"

networks:
  scanner-network:
    driver: bridge
